# Generated by Django 4.0.6 on 2022-07-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=122)),
                ('lname', models.CharField(max_length=122)),
                ('emaill', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=122)),
                ('contactno', models.CharField(max_length=10)),
            ],
        ),
    ]
