# Generated by Django 4.0.6 on 2022-07-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emaill', models.CharField(max_length=122)),
                ('feedbacki', models.TextField(max_length=400)),
            ],
        ),
    ]
